# Generated by Django 5.2.3 on 2026-06-04 02:16

import baseapp_comments.models
import baseapp_comments.validators
import baseapp_reactions.models
import baseapp_reports.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "reports_count",
                    models.JSONField(
                        default=baseapp_reports.models.default_reports_count
                    ),
                ),
                (
                    "reactions_count",
                    models.JSONField(
                        default=baseapp_reactions.models.default_reactions_count,
                        editable=False,
                    ),
                ),
                ("is_reactions_enabled", models.BooleanField(default=True)),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(
                        default=True, verbose_name="is comments enabled"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            baseapp_comments.validators.blocked_words_validator
                        ],
                        verbose_name="body",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="languaged used in the comment",
                        max_length=10,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="is edited"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="is pinned"),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="target object id",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "deleted"), (1, "published")],
                        db_index=True,
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "in_reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.BASEAPP_COMMENTS_COMMENT_MODEL,
                        verbose_name="in reply to",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["-is_pinned", "-created"],
                "permissions": [
                    ("pin_comment", "can pin comments"),
                    ("report_comment", "can report comments"),
                    ("view_all_comments", "can view all comments"),
                    ("add_comment_with_profile", "can add comments with profile"),
                ],
                "abstract": False,
                "swappable": "BASEAPP_COMMENTS_COMMENT_MODEL",
            },
        ),
    ]
