# Generated by Django 5.2.3 on 2026-06-04 02:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "content_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_types",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_types",
                        to=settings.BASEAPP_REPORTS_REPORTTYPE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_REPORTS_REPORTTYPE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("report_subject", models.TextField(blank=True, null=True)),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.BASEAPP_REPORTS_REPORTTYPE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_REPORTS_REPORT_MODEL",
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="baseapp_rep_target__171117_idx",
                    )
                ],
                "unique_together": {
                    ("user", "target_content_type", "target_object_id")
                },
            },
        ),
    ]
