# Generated by Django 5.2.3 on 2026-06-04 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("baseapp_blocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocking",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                verbose_name="blocking",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blockers",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                verbose_name="blockers",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["target", "actor"], name="baseapp_blo_target__031766_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("actor", "target")},
        ),
    ]
