# Generated by Django 5.2.3 on 2026-06-04 02:16

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("baseapp_chats", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="created_by_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_created_rooms",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroomparticipant",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroomparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="action_object_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_object",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content_linked_profile_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_as_content_actor_set",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content_linked_profile_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_as_content_target_set",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unreadmessagecount",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unreadmessagecount",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unread_messages",
                to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="set_last_message",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            UPDATE baseapp_chats_chatroom\n            SET last_message_id = NEW.id, last_message_time = NEW.created\n            WHERE id = NEW.room_id;\n            RETURN NULL;\n        ",
                    hash="06f966e2a58859020db8c4fe063d60775823bc1a",
                    operation="INSERT",
                    pgid="pgtrigger_set_last_message_9c677",
                    table="baseapp_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="create_message_status",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."message_type" = 1)',
                    func="\n            INSERT INTO baseapp_chats_messagestatus (message_id, profile_id, is_read)\n            SELECT NEW.id, crp.profile_id, CASE WHEN NEW.profile_id = crp.profile_id THEN TRUE ELSE FALSE END\n            FROM baseapp_chats_chatroomparticipant as crp\n            WHERE crp.room_id = NEW.room_id;\n            RETURN NULL;\n        ",
                    hash="beb46ab0586aff0156230e06f0f378f3af30b54b",
                    operation="INSERT",
                    pgid="pgtrigger_create_message_status_c941b",
                    table="baseapp_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="update_last_message",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            UPDATE baseapp_chats_chatroom\n            SET last_message_id = (\n                SELECT id\n                FROM baseapp_chats_message\n                WHERE room_id = OLD.room_id\n                ORDER BY created DESC\n                LIMIT 1\n            ),\n            last_message_time = (\n                SELECT created\n                FROM baseapp_chats_message\n                WHERE room_id = OLD.room_id\n                ORDER BY created DESC\n                LIMIT 1\n            )\n            WHERE id = OLD.room_id;\n            RETURN NULL;\n        ",
                    hash="185b6146e2a5bbec3fb6668180701954aebaaaa3",
                    operation="DELETE",
                    pgid="pgtrigger_update_last_message_e519b",
                    table="baseapp_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagestatus",
            unique_together={("message_id", "profile_id")},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="increment_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NOT NEW."is_read")',
                    func="\n            INSERT INTO baseapp_chats_unreadmessagecount (room_id, profile_id, marked_unread, count)\n            VALUES ((SELECT room_id FROM baseapp_chats_message WHERE id = NEW.message_id), NEW.profile_id, False, 1)\n            ON CONFLICT (room_id, profile_id)\n            DO UPDATE SET count = baseapp_chats_unreadmessagecount.count + 1;\n            RETURN NULL;\n        ",
                    hash="e18409b9d00a1d881dabf9b7aaa8da101ac5ac28",
                    operation="INSERT",
                    pgid="pgtrigger_increment_unread_count_ec3cd",
                    table="baseapp_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="decrement_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."is_read" AND NOT OLD."is_read")',
                    func="\n            UPDATE baseapp_chats_unreadmessagecount\n            SET count = GREATEST(0, count - 1)\n            WHERE\n                room_id = (SELECT room_id FROM baseapp_chats_message WHERE id = NEW.message_id) AND\n                profile_id = NEW.profile_id;\n            RETURN NULL;\n        ",
                    hash="08effa83237ad55cf10b5eb25e6fc9e824799b14",
                    operation="UPDATE",
                    pgid="pgtrigger_decrement_unread_count_a1c0b",
                    table="baseapp_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unreadmessagecount",
            unique_together={("room_id", "profile_id")},
        ),
    ]
