# Generated by Django 4.2.3 on 2024-04-09 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_auth", "0003_superuserupdatelog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superuserupdatelog",
            options={"ordering": ["id"]},
        ),
    ]
