# Generated by Django 4.2.3 on 2024-04-09 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_auth", "0007_alter_superuserupdatelog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superuserupdatelog",
            options={"ordering": ["created"]},
        ),
    ]
