# Generated by Django 4.2.3 on 2024-05-26 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_auth", "0010_alter_superuserupdatelog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superuserupdatelog",
            options={},
        ),
    ]
