# Generated by Django 5.2.3 on 2026-06-04 02:16

import baseapp_comments.models
import baseapp_core.models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pghistory", "0006_delete_aggregateevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(
                        default=True, verbose_name="is comments enabled"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "body_en",
                    django_quill.fields.QuillField(
                        blank=True, null=True, verbose_name="body"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "Published")],
                        db_index=True,
                        default=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "swappable": "BASEAPP_PAGES_PAGE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_robots",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meta_og_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meta_og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in(
                            "pages/metadata/og_image"
                        ),
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("target_content_type", "target_object_id", "language")
                },
            },
        ),
        migrations.CreateModel(
            name="MetadataEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_robots",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meta_og_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meta_og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in(
                            "pages/metadata/og_image"
                        ),
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="baseapp_pages.metadata",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="URLPath",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("path", models.CharField(max_length=500, unique=True)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL Path",
                "verbose_name_plural": "URL Paths",
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="metadata",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_pages_metadataevent" ("created", "id", "language", "meta_description", "meta_og_image", "meta_og_type", "meta_robots", "meta_title", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_content_type_id", "target_object_id") VALUES (NEW."created", NEW."id", NEW."language", NEW."meta_description", NEW."meta_og_image", NEW."meta_og_type", NEW."meta_robots", NEW."meta_title", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="deb5e56df169fc75ebbb20f54749648c636dadfa",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_77686",
                    table="baseapp_pages_metadata",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="metadata",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "baseapp_pages_metadataevent" ("created", "id", "language", "meta_description", "meta_og_image", "meta_og_type", "meta_robots", "meta_title", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_content_type_id", "target_object_id") VALUES (NEW."created", NEW."id", NEW."language", NEW."meta_description", NEW."meta_og_image", NEW."meta_og_type", NEW."meta_robots", NEW."meta_title", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="129d6d409800f020c1454b4a8c0526209632b236",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_a7a1e",
                    table="baseapp_pages_metadata",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="metadata",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_pages_metadataevent" ("created", "id", "language", "meta_description", "meta_og_image", "meta_og_type", "meta_robots", "meta_title", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_content_type_id", "target_object_id") VALUES (OLD."created", OLD."id", OLD."language", OLD."meta_description", OLD."meta_og_image", OLD."meta_og_type", OLD."meta_robots", OLD."meta_title", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."target_content_type_id", OLD."target_object_id"); RETURN NULL;',
                    hash="cbb78e825a3e4830f3a6847f8348c5995c673078",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_be121",
                    table="baseapp_pages_metadata",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="urlpath",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="baseapp_pag_target__0566b8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="urlpath",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("path", "language"),
                name="unique_active_path",
            ),
        ),
    ]
