# Generated by Django 4.2.3 on 2024-03-27 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("baseapp_files", "0002_remove_file_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="parent_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="parent_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileevent",
            name="parent_content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="fileevent",
            name="parent_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
