# Generated by Django 4.2.3 on 2024-04-09 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_files", "0003_alter_file_parent_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["id"]},
        ),
    ]
