# Generated by Django 4.2.3 on 2024-04-09 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_files", "0004_alter_file_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={},
        ),
    ]
