# Generated by Django 5.2.3 on 2026-06-04 02:16

import baseapp_comments.models
import baseapp_core.models
import baseapp_reports.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "blockers_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "blocking_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "followers_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "following_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "reports_count",
                    models.JSONField(
                        default=baseapp_reports.models.default_reports_count
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(
                        default=True, verbose_name="is comments enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in("profile_images"),
                        verbose_name="image",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in(
                            "profile_banner_images"
                        ),
                        verbose_name="banner image",
                    ),
                ),
                (
                    "biography",
                    models.TextField(blank=True, null=True, verbose_name="biography"),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="target object id"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "public"), (2, "private")], default=1
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="contenttypes.contenttype",
                        verbose_name="target content type",
                    ),
                ),
            ],
            options={
                "permissions": [("use_profile", "can use profile")],
                "abstract": False,
                "swappable": "BASEAPP_PROFILES_PROFILE_MODEL",
                "unique_together": {("target_content_type", "target_object_id")},
            },
        ),
        migrations.CreateModel(
            name="ProfileUserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "admin"), (2, "manager")], default=2
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "active"), (2, "pending"), (3, "inactive")],
                        default=2,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                        verbose_name="profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_PROFILES_PROFILEUSERROLE_MODEL",
                "unique_together": {("user", "profile")},
            },
        ),
    ]
