# Generated by Django 4.2.3 on 2024-03-27 22:56

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_pages", "0003_remove_page_snapshot_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="snapshot_delete",
        ),
        migrations.RemoveField(
            model_name="page",
            name="body_es",
        ),
        migrations.RemoveField(
            model_name="page",
            name="body_pt",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_pt",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="body_es",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="body_pt",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="title_pt",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_pages_pageevent" ("body_en", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "status", "title_en", "user_id") VALUES (NEW."body_en", NEW."comments_count", NEW."created", NEW."id", NEW."is_comments_enabled", NEW."modified", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 1, NEW."status", NEW."title_en", NEW."user_id"); RETURN NULL;',
                    hash="de5d7d82c40257ae4f636eaf2d965117d78a0b6d",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_f0c08",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "baseapp_pages_pageevent" ("body_en", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "status", "title_en", "user_id") VALUES (NEW."body_en", NEW."comments_count", NEW."created", NEW."id", NEW."is_comments_enabled", NEW."modified", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 2, NEW."status", NEW."title_en", NEW."user_id"); RETURN NULL;',
                    hash="2be4f033ac69e150bafdfa5d6a27a01a2dedc1e2",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_845c1",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_pages_pageevent" ("body_en", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "status", "title_en", "user_id") VALUES (OLD."body_en", OLD."comments_count", OLD."created", OLD."id", OLD."is_comments_enabled", OLD."modified", _pgh_attach_context(), NOW(), \'snapshot\', OLD."id", 3, OLD."status", OLD."title_en", OLD."user_id"); RETURN NULL;',
                    hash="f3b746509f44c07045e02ef8eba071988c715f2e",
                    operation="DELETE",
                    pgid="pgtrigger_snapshot_delete_caf3a",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
