# Generated by Django 4.2.3 on 2024-04-09 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_pages", "0004_remove_page_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["id"]},
        ),
    ]
