# Generated by Django 4.2.3 on 2024-04-09 20:42

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_pages", "0005_alter_page_options"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="snapshot_delete",
        ),
        migrations.RemoveField(
            model_name="page",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_comments_enabled",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="is_comments_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_pages_pageevent" ("body_en", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "status", "title_en", "user_id") VALUES (NEW."body_en", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 1, NEW."status", NEW."title_en", NEW."user_id"); RETURN NULL;',
                    hash="55f4f049fabff1f292e2afbddbdc19556943d88f",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_f0c08",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "baseapp_pages_pageevent" ("body_en", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "status", "title_en", "user_id") VALUES (NEW."body_en", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 2, NEW."status", NEW."title_en", NEW."user_id"); RETURN NULL;',
                    hash="1f11b3150e1528b485ef21813b87803030118168",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_845c1",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_pages_pageevent" ("body_en", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "status", "title_en", "user_id") VALUES (OLD."body_en", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'snapshot\', OLD."id", 3, OLD."status", OLD."title_en", OLD."user_id"); RETURN NULL;',
                    hash="7cdabf6238b162b8badd513fc5fe12428aada391",
                    operation="DELETE",
                    pgid="pgtrigger_snapshot_delete_caf3a",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
