# Generated by Django 5.2.3 on 2026-06-04 02:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (
                                "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
                                "User Attribute Similarity",
                            ),
                            (
                                "django.contrib.auth.password_validation.MinimumLengthValidator",
                                "Minimum Length",
                            ),
                            (
                                "django.contrib.auth.password_validation.CommonPasswordValidator",
                                "Common Password",
                            ),
                            (
                                "django.contrib.auth.password_validation.NumericPasswordValidator",
                                "Numeric Password",
                            ),
                            (
                                "baseapp_auth.password_validators.MustContainCapitalLetterValidator",
                                "Must Contain Capital Letter",
                            ),
                            (
                                "baseapp_auth.password_validators.MustContainSpecialCharacterValidator",
                                "Must Contain Special Character",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuperuserUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("made_superuser", models.BooleanField()),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superuser_assignee_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superuser_assigner_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
